# Etapa 1: Build
FROM node:18-alpine AS builder

WORKDIR /app

# Copiar apenas os ficheiros essenciais
COPY package.json pnpm-lock.yaml ./

# Instalar pnpm e dependências
RUN npm install -g pnpm && pnpm install

# Copiar restante do código
COPY . .

# Build do projeto Vite
RUN pnpm run build

# Etapa 2: Produção
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
