version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bun-backend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./backend/src:/app/src
    command: bun src/index.ts

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite-frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  websocket:
    build:
      context: ./sockets
      dockerfile: Dockerfile
    container_name: websocket-server
    ports:
      - "8080:8080"
    working_dir: /app
    command: node server.js